version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dkpbotstack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kt90vj9sjdw6"
s3_prefix = "dkpbotstack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
